update mobile pipeline

diff --git a/.github/workflows/security.yaml b/.github/workflows/security.yaml
--- a/.github/workflows/security.yaml
+++ b/.github/workflows/security.yaml
@@ -57,6 +57,15 @@ jobs:
           persist-credentials: false
           path: ./${{ inputs.repository }}
 
+      - name: Verify APK File
+        run: |
+          if [ ! -f "${{ inputs.path-app }}" ]; then
+            echo "ERROR: APK file not found at ${{ inputs.path-app }}"
+            exit 1
+          else
+            echo "APK file found: ${{ inputs.path-app }}"
+          fi
+
       - name: Run MobSF Scan
         if: ${{ inputs.path-app != '' }}
         env:
